---
title: "Chongkyung Jason Kim"
output:
  html_notebook: default
---

```{r}

```



267-453-6620 | ckim4@g.harvard.edu | [my website](https://jasonkyungkim.github.io) | [linkedin](https://www.linkedin.com/in/jasonkyungkim/) | [github](https://github.com/jasonkyungkim)

<!-- #### Education -->
<!-- Harvard University, SM in Data Science                  Dec 2023 -->

#### **Education**:

- **Harvard University**, SM in Data Science                              
- **Swarthmore College**, BA in Mathematics and Statistics
  * **Surdna Summer Fellow** & **Leedom Fellow**: received scholarship for data science research and graduate studies
  * **Teaching Assistant**: 
    - MATH 39: Discrete Mathematics 
    - All statistics courses at the college, including: 
      - STAT 011: Statistical Methods I
      - STAT 021: Statistical Methods II
      - STAT 051: Probability 
      - STAT 061: Mathematical Statistics I
      - STAT 111: Mathematical Statistics II

#### **Experience**:

##### Data Science Intern @ The Hershey Company
  - Leverage behavioral data to predict users’ satisfaction with their ad experience

##### Undergraduate Researcher @ Steve Wang Lab | [View Research Poster](https://jasonkyungkim.github.io/whale_poster.pdf)
  - Estimated the population size of North Atlantic right whales, an endangered species, using logistic regression under a Bayesian framework.
  - Found errors in the North Atlantic Right Whale Consortium (NARWC) dataset that contradicted relevant papers; reported to NARWC for correction
  - Computed point estimate that was within the 95\% confidence interval of other top NARWC papers' models
  - Added 13 new features and controlled multicolinearity, reducing the false positive rate by 60\%, while keeping the false negative the same
  - Implemented a parallelized algorithm that improved runtime of the main simulation algorithm by 40\%
  - Presented results to an audience of 450+ at the annual NARWC conference
  
##### Data Engineering Intern @ Telnyx
- One of the three founding members of the data engineering team
- Developed Airflow tasks and built supporting pipelines to automate getting data from different internal and external API endpoints to process and backup into the PostgreSQL databases and AWS S3 buckets

##### Data Science Intern @ LotusFlare
- Studied engineers' workflow behavior with Jira to increase engagement
- Built an automated email tool that reminds engineers of ticket deadlines; increased Jira ticket completion rate among engineers by 30 percent
- Reported data analysis findings in bi-weekly meetings to 30+ engineers and product managers

#### **Projects** | [Link to all projects](https://jasonkyungkim.github.io/projects.html):

##### The Interconnectedness of Deforestation, Ocean Levels, and Carbon Emissions (In Progress) | [View on Github](https://github.com/jasonkyungkim/climate_challenge)
- Exploring the relationship between deforestation, rising ocean levels, and increasing carbon emissions with ML models

##### Predicting the English Premier League Table (In progress) | [View on Github](https://nbviewer.org/github/jasonkyungkim/pl_prediction/blob/main/pl_stadings.ipynb)
- Use machine learning models such as XGBoost and Neural Networks to predict Premier League standings

##### The Manchester United Diagnosis | [View on Github](https://nbviewer.org/github/jasonkyungkim/manchester-data/blob/main/manutd_analysis.ipynb)
- Performed Exploratory Data Analysis (EDA) on football data, scraped from online with BeautifulSoup
- Found that United overspent on players with inflated-stats but little actual value which lead to poor performances